AWSTemplateFormatVersion: "2010-09-09"
Description: |
  this is a compute example.
Parameters:
  BucketName:
    Type: String
    Default: my-website-822014814477
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  MYHomeCIDR:
    Description: my Home ip
    Type: String
    Default: 196.221.189.130/32
Resources:
  JumpboxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue IaC-VPC
      GroupDescription: Allow SSH from my home address ip
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MYHomeCIDR

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue IaC-VPC
      GroupDescription: Allow HTTP from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue IaC-VPC
      GroupDescription: Allow SSH from Jumpbox and HTTP from the ALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref JumpboxSecurityGroup
  
  EC2S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  S3AccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource: !Sub "arn:aws:s3:::${BucketName}"
      Roles:
        - !Ref EC2S3AccessRole

  WebServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2S3AccessRole


  WebServerAutoScalingLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceType: t2.medium
      ImageId: !Ref AmiID
      KeyName: IaCKey
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      IamInstanceProfile: !Ref WebServerInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 10
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          apt update -y
          apt install apache2 awscli -y

          systemctl start apache2.service
          systemctl enable apache2.service

          aws s3 sync s3://${BucketName} /var/www/html

  WebServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
    Properties:
      LaunchConfigurationName: !Ref WebServerAutoScalingLaunchConfiguration
      MinSize: "2"
      MaxSize: "4"
      DesiredCapacity: "2"

      VPCZoneIdentifier:
        - !ImportValue IaC-Private-Subnet-1
        - !ImportValue IaC-Private-Subnet-2

      TargetGroupARNs:
        - !Ref ElasticLoadBalancingTargetGroup

  WebServerAutoScalingCPUScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref WebServerAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50

    
  ElasticLoadBalancingTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue IaC-VPC
      Protocol: HTTP
      Port: 80
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5

  ElasticLoadBalancingLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: 
        - !ImportValue IaC-Public-Subnet-1
        - !ImportValue IaC-Public-Subnet-2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  ElasticLoadBalancingListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ElasticLoadBalancingTargetGroup
      LoadBalancerArn: !Ref ElasticLoadBalancingLoadBalancer
      Port: 80
      Protocol: HTTP

  ElasticLoadBalancingListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ElasticLoadBalancingTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - "/*"
      ListenerArn: !Ref ElasticLoadBalancingListener
      Priority: 1


  Jumpbox1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref AmiID
      KeyName: jumbox
      SecurityGroupIds:
        - !Ref JumpboxSecurityGroup
      SubnetId: !ImportValue IaC-Public-Subnet-1
      Tags:
        - Key: Name
          Value: IaC-Jumpbox-1

  Jumpbox2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref AmiID
      KeyName: jumbox
      SecurityGroupIds:
        - !Ref JumpboxSecurityGroup
      SubnetId: !ImportValue IaC-Public-Subnet-2
      Tags:
        - Key: Name
          Value: IaC-Jumpbox-2

Outputs:
  Jumpbox1PublicIPAddress:
    Description: The Public IP Address of Jumpbox 1
    Value: !GetAtt Jumpbox1.PublicIp

  Jumpbox2PublicIPAddress:
    Description: The Public IP Address of Jumpbox 2
    Value: !GetAtt Jumpbox2.PublicIp

  LoadBalancerDNSName:
    Description: DNS Name of the web application
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt ElasticLoadBalancingLoadBalancer.DNSName
    Export:
      Name: IaC-APP-ELB-DNS-Name
